### ISSUE TITLE
(Not) Evaluating Logical Expressions with addError() and addWarning()

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/ParameterCheck#3]
Sometimes we don't necessarily wish to evaluate a logical expression in our error messaging. Other times we want to both evaluate a logical expression and do some other stuff while checking.

```
JSD <- function(data, gp){
  ck <- ArgumentCheck::newArgCheck()
  ck <- ArgumentCheck::addError(is.data.frame(data), "'data' must be a data frame", ck)
  ck <- ArgumentCheck::addError(length(intersect(class(gp),c("character","factor")))>0,
                                "'gp' must be either the name of a factor variable in 'data' or a factor",
                                ck)
  finishArgCheck(ck)
  n <- nrow(data)

  ##########################################################
  # Note that I had to evaluate 'length(gp)>1' twice here
  ##########################################################
  if(is.character(gp)){
    ck <- ArgumentCheck::addWarning(length(gp)>1,
                                    "'gp' is a character vector of length >1. Using only the first element",
                                    ck)
    if(length(gp)>1) gp <- gp[1]
  }
  else if(is.factor(gp)){
    ck <- ArgumentCheck::addError(length(gp) == n,
                                  "factor 'gp' must have same length as number of rows in 'data'",
                                  ck)
  }
  ##########################################################
  # Note that I had to evaluate 'TRUE' here. 
  # Maybe making 'expr' an optional parameter would be good.
  # Or...what about setting 'expr=TRUE" by default?
  ##########################################################
  else Check <- ArgumentCheck::addError(TRUE,
                                        msg = "'gp' must be a numeric array",
                                        argcheck = Check)

}

```

**Comment by nutterb** [comment]
Can you tell I don't have anything productive to do today? :)

with your first note, I would actually approach it with

```
if (is.character(gp)){
  if (length(gp) > 1){
    ArgumentCheck::addWarning(TRUE,
             msg = "'gp' is a character.....",
             ck)
    gp <- gp[1]
  }
}
```

For the second note, this is actually how I intended for it to be used in these situations.  I'm considering your suggestion about setting `expr=TRUE` as a default.  The only downside is that I don't want to move the position, and so if you don't specify it, you're forced to type `msg=`, which is just as many key strokes.  So I guess the only question is if I want to force the user to be explicit.  (I shouldn't be allowed to have this much control).

By the way, when I get home this evening, I'll push up some updates from my local computer (I thought I already had, but they aren't there).  The `devel` branch will use an environment to capture the errors and warnings instead of a list.  This has a couple of advantages, such as reducing key strokes and more importantly, it will allow me to write other functions that actually do things while still having access to the error buffer.  I'd recommend installing the updated version from GitHub and developing in that.  I'll get the updates the CRAN early next week.  I just need to do a little more testing first.

``` r
# The appearance with the environment version
ck <- ArgumentCheck::newArgCheck() 
ArgumentCheck::addError(!is.data.frame(data), "'data' must be a data frame", ck)

ArgumentCheck::finishArgCheck(ck)
```

**Comment by jarrod-dalton** [comment]
And here's yet another option:

```
check(expr, obj)
```

where `obj` is either an 'ArgumentError' or `ArgWarning` object, created by functions `err()` and `warn()`, respectively.

Examples:

```
if (is.character(gp)){
  if (length(gp) > 1){
    ArgumentCheck::warn(msg = "'gp' is a character.....",   ck)  #basically AddWarning() w/o the expr
    gp <- gp[1]
  }
}
```

```
if (is.character(gp)){
  ArgumentCheck::check(length(gp)>1, warn(msg = "'gp' is a character.....",   ck))
  if (length(gp) > 1) gp <- gp[1]
}
```

And, finally, if you allowed the user to pass a block of code somehow, you could do:

```
if (is.character(gp)){
  ArgumentCheck::check(length(gp)>1,
           obj = warn(msg = "'gp' is a character.....", ck),
           code = "if (length(gp) > 1) gp <- gp[1]")

}
```

**Comment by nutterb** [comment]
You might have me sold on removing the `expr` argument.  I'll probably leave it as

``` r
if (is.character(gp)){
  if (length(gp) > 1){
    ArgumentCheck::addWarning("'gp' is a character...", ck)
    gp <-gp[1]
  }
}

ArgumentCheck::finishArgCheck(ck)
```

My only hesitation is that it destroys back compatibility, but 1) I was going to run into those issues with the move to environments, and 2) no one is really using it anyway.  So I think I might switch to the environments and drop the `expr` argument. 

Yeah, I feel good about that.
