### ISSUE TITLE
TRUE or FALSE...that is the question

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/ParameterCheck#4]
This is a style thing, but I would tend to want the `expr` argument to evaluate to FALSE in order for `addError()` and `addWarning()` to append a message to the `argcheck` object.  Because we're "checking" arguments to meet certain logical expressions.

**Comment by nutterb** [comment]
This one I don't think I'll agree with.  

``` r
addError(TRUE, "Error Message")
```

seems a lot more cognitively consistent than

``` r
addError(FALSE, "Error Message")
```

The first seems to say "add the error when..." and the second says "avoid the error when..."

That being said, I sometimes mix it up as well.  So it isn't just you.  Perhaps I could put in a companion function like

``` r
validArg(expr = valid condition, msg, argcheck, type = c("error", "warning")){
  if (type == "error") addError(!expr, msg, argcheck)
  if (type == "warning") addWarning(!expr, msg, argcheck)
}
```

Would that satisfy your style?  Is there a pair of function names I could use rather than using `validArg` for both errors and warnings?

**Comment by jarrod-dalton** [comment]
6 of one and half a dozen of the other.  

it could be more explicit by not having the `expr` argument in the function:

if(expr) addError("Error Message", ArgCheckObject)

This would behave similarly to `stop()`, but wouldn't actually stop until you told it to.

It would also allow for doing other stuff with the argument being checked in `expr`.  But then `addError()` would be naive to which argument is being checked in `expr`.

Another option would be to allow for passing a block of code wrapped in curly braces to these functions.

Or just leave it alone.

**Comment by nutterb** [comment]
As stated in Issue #3, I'll be removing the `expr` argument.
